### ISSUE TITLE
AspNET tutorial fails due to the scope defined.

### ISSUE THREAD

**Issue by fiannolo** [auth0/auth0-aspnet#14]
The file /Views/Shared/_Layout.cshtml has defined the scope to get the entire profile and sometimes it fails. To ensure that the seed project always works, the scope should be changed to get only 1 field just like the tutorial specifies.
![image](https://cloud.githubusercontent.com/assets/18537446/18147940/faf7a43a-6fa4-11e6-80a7-5e18cab4b4a7.png)
![image](https://cloud.githubusercontent.com/assets/18537446/18147972/30e18520-6fa5-11e6-938a-6bf665df1ed4.png)

**Comment by jerriep** [comment]
@fiannolo The ASP.NET tutorial has been completely reworked, and in the new format it includes the correct HTML/JavaScript in the tutorial

Please see https://auth0.com/docs/quickstart/webapp/aspnet-owin

Let me know if you still have issues
