### ISSUE TITLE
ASP NET Regular Web App Seed Project Crashes after adding further reading code.

### ISSUE THREAD

**Issue by fiannolo** [auth0/auth0-aspnet#15]
When the seed project is downloaded and you try to add these lines of code to the `web.config` like it is described in the ` Redirecting to a Login Page` section to start using the [Authorize] decorator.
```
<system.web>
  <authentication mode="Forms">
    <forms loginUrl="Account/Login" />
  </authentication>
</system.web>
```
The application throws an exception

![image](https://cloud.githubusercontent.com/assets/18537446/19175351/c30d4e6e-8c03-11e6-9fbc-ab491b8d4211.png)

I have tested it in Visual Studio 2015 Enterprise Edition.

Additional information. 

After reviewing this information and a few tests, when those lines are added to the web config, the first time that the page loads, the ClaimsPrincipal.Current.Claims.Any() returns true, and if that information is commented, the method returns false.

We have received a ticket about this and to solve the problem and help the user continue with this tests we have suggested to add to the Index Method the following code

```
    public ActionResult Index()
        {
            var currentClaims = ClaimsPrincipal.Current;
            
            if (currentClaims.Claims.Any())
            {
                if (currentClaims.FindFirst("name") != null)
                {
                    string name = currentClaims.FindFirst("name").Value;
                    ViewBag.Name = name;
                    
                }
               
               
                
            }
            else 
              ViewBag.Name = "";
               
            return View();
        }
```
Which doesn't solve the problem but force the app to continue running even when the currentClaims.Claims is filled with information that is not correct.

After that modification the seed project runs properly.

**Comment by jerriep** [comment]
@fiannolo I made changes to fix this error. Changes are required to both the `HomeController.cs` and the `Index.cshtml` file. 

See https://github.com/auth0/auth0-aspnet/commit/688ce5707587ffb0f36b711763e77c3f5395e620 for more information on changes
