### ISSUE TITLE
Unable to install Auth0 package in VS 2013 .Net Framework 4.0

### ISSUE THREAD

**Issue by kshkrao3** [auth0/auth0-aspnet#18]
I was trying to install Auth0 package for my rest-api which is targeting .Net Framework 4.0 but I keep getting below error.

**Could not install package 'Auth0.AuthenticationApi 3.6.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.**

I am not supposed to change the .Net framework version from 4.0. Is there anyway still I can use this in my project?

**Addendum**

When I try to install `Auth0-AspNet` I get same error for different package.

**Could not install package 'Auth0.Core 3.3.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.**

Hope to find some help soon.

**Comment by chenkie** [comment]
@jerriep can you take a look? :)

**Comment by kshkrao3** [comment]
@chenkie @jerriep Could anyone please help me on this.. :(

**Comment by kshkrao3** [comment]
@chenkie Any updates on this please?

**Comment by chenkie** [comment]
@kshkrao3 we should have something shortly, stay tuned :)

**Comment by kshkrao3** [comment]
@chenkie Thanks much for the prompt response.. :)

**Comment by jerriep** [comment]
Hi @kshkrao3 

My apologies. I unpublished some of the older Auth0 NuGet packages which meant that the Auth0-ASPNET NuGet package could not take the right dependencies.

I fixed this, and you should now be able to install Auth0-ASPNET correctly into a .NET 4.0 project.

**Comment by kshkrao3** [comment]
Thanks much @jerriep and @chenkie .. Really appreciate the help on this. Works flawlessly now.. :)

**Comment by kshkrao3** [comment]
@jerriep and @chenkie I am facing a new Issue now with `JsonWebToken.cs`. I am getting various build errors like

- **'Claim' does not contain a definition for 'Type' and no extension method 'Type' accepting a first argument of type 'Claim' could be found (are you missing a using directive or an assembly reference?)`**

- **'ClaimsIdentity' does not contain a definition for 'AddClaim' and no extension method 'AddClaim' accepting a first argument of type 'ClaimsIdentity' could be found (are you missing a using directive or an assembly reference?)**

- **'Task' does not contain a definition for 'FromResult' - App_Start\JsonWebTokenValidationHandler.cs**

- **Argument 1: cannot convert from 'Microsoft.IdentityModel.Claims.ClaimsIdentity' to 'System.Security.Principal.IPrincipal'**.

Hopefully, even these are because of .Net Framework 4.0. Could you please look into these and let me know if I have any solution for this? Should I open it as separate issue?

**Comment by jerriep** [comment]
@kshkrao3 , unfortunately there is no way around this one. The `ClaimsPrincipal` class for example is only available from .NET 4.5 onwards (see the docs at https://msdn.microsoft.com/en-us/library/system.security.claims.claimsprincipal(v=vs.110).aspx)

Same for the `Claim` class (see https://msdn.microsoft.com/en-us/library/system.security.claims.claim(v=vs.110).aspx)

The errors you are now getting is because you imported other namespace to try and resolve those classes (in this case it seems the Microsoft.IdentityModel.Claims namespace), and that will not work.

Is there a reason you cannot move to .NET 4.5

**Comment by kshkrao3** [comment]
@jerriep Yes Sir. I cannot move this project to .NET 4.5 because, the server am hosting this API supports only until .NET 4.0. Its a Bigrock server [Parallel Plesk] and hence unfortunately, am supposed to stick to it. Any other work around I can find for the above issue, or I just need to drop this off and try a different way to authorize the API requests?

**Comment by jerriep** [comment]
@kshkrao3 Unfortunately the JWT middleware we supply does not support .NET 4.5.

In this case you will unfortunately have to validate the JWT yourself, perhaps using a library such as Jose-JWT (https://www.nuget.org/packages/jose-jwt/)

**Comment by kshkrao3** [comment]
@jerriep Alright Sir. I will see how I can integrate with this. Thanks much for your time once again. :)
