### ISSUE TITLE
Unable to authenticate using SSO

### ISSUE THREAD

**Issue by adamtay** [auth0/auth0-aspnet#23]
I'm trying to implement single sign on between two ASP.NET MVC applications.
The implementation can be found [here on my github](https://github.com/adamtay/Auth0.Playground/tree/master/AspNetMvc.SSO)
Inside my git repository, I have two projects, AspNetMVC.SSO and AspNetMvc.SSO2 which both contain identical code and are using the same Auth0 client configurations.

Auth0 lock implementation code can be found [here](https://github.com/adamtay/Auth0.Playground/blob/master/AspNetMvc.SSO/AspNetMvc.SSO2/Views/Home/Index.cshtml)
LoginCallback implementation code can be found [here](https://github.com/adamtay/Auth0.Playground/blob/master/AspNetMvc.SSO/AspNetMvc.SSO2/LoginCallback.ashx.cs)

In my application, I'm using Auth0 Lock v10.15, Auth0js v7.6.1 and Auth0.AspNet 1.6.0 for the MVC application.
I have set up my project AspNetMvc.SSO as http://app.com:8080 and AspNetMvc.SSO2 as http://app2.com:8081

If I login to http://app.com:8080 (app1) and  navigate to http://app2.com:8081 (app2) which should authenticate using sso, I can get the sso payload using auth0.getSSOData(). However, once it sends the payload to the LoginCallback (/LoginCallback.ashx) to authenticate, it is unable to execute the method await client.ExchangeCodeForAccessTokenAsync() as context.Request.QueryString["code"] is null.

Looking at the sso payload that is sent to the LoginCallback, it contains all the data to initialize the AccessToken object.
What am I missing here to get the SSO payload working with the default LoginCallback implementation?

**Comment by jerriep** [comment]
Hi Adam

I am going to ask you to please go through the support channels for this one. The appropriate support channel will depend on the type of subscription you have.

For more information please see https://auth0.com/docs/support

Thanks
