### ISSUE TITLE
auth0-aspnet-mvc4-sample no oidcConformant and audience parameter

### ISSUE THREAD

**Issue by Amialc** [auth0/auth0-aspnet#24]
(AUTH-3959)
[auth0-aspnet-mvc4-sample](https://github.com/auth0/auth0-aspnet/blob/master/examples/auth0-aspnet-mvc4-sample/aspnet4-sample1/Views/Shared/_Layout.cshtml#L48) doesn't provide oidcConformant and audience parameters to auth0-lock

**Comment by jerriep** [comment]
Closed with PR#27
